# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:/jingyan/MA ABSCHLUSS/MA/MA(CODE)/GUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1319, 736)
        self.originalImage = QtWidgets.QGraphicsView(Dialog)
        self.originalImage.setGeometry(QtCore.QRect(400, 60, 281, 221))
        self.originalImage.setObjectName("originalImage")
        self.segmentedImage = QtWidgets.QGraphicsView(Dialog)
        self.segmentedImage.setGeometry(QtCore.QRect(710, 60, 281, 221))
        self.segmentedImage.setObjectName("segmentedImage")
        self.clearSelection = QtWidgets.QPushButton(Dialog)
        self.clearSelection.setGeometry(QtCore.QRect(210, 240, 161, 41))
        self.clearSelection.setObjectName("clearSelection")
        self.textBrowser = QtWidgets.QTextBrowser(Dialog)
        self.textBrowser.setGeometry(QtCore.QRect(20, 60, 351, 161))
        self.textBrowser.setObjectName("textBrowser")
        self.textBrowser_2 = QtWidgets.QTextBrowser(Dialog)
        self.textBrowser_2.setGeometry(QtCore.QRect(400, 20, 281, 31))
        self.textBrowser_2.setObjectName("textBrowser_2")
        self.textBrowser_3 = QtWidgets.QTextBrowser(Dialog)
        self.textBrowser_3.setGeometry(QtCore.QRect(710, 20, 281, 31))
        self.textBrowser_3.setObjectName("textBrowser_3")
        self.line = QtWidgets.QFrame(Dialog)
        self.line.setGeometry(QtCore.QRect(30, 290, 1271, 21))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.embeddingsView = QtWidgets.QGraphicsView(Dialog)
        self.embeddingsView.setGeometry(QtCore.QRect(400, 320, 591, 391))
        self.embeddingsView.setObjectName("embeddingsView")
        self.chooseEmbeddingDirs = QtWidgets.QPushButton(Dialog)
        self.chooseEmbeddingDirs.setGeometry(QtCore.QRect(30, 600, 341, 41))
        self.chooseEmbeddingDirs.setObjectName("chooseEmbeddingDirs")
        self.textBrowser_4 = QtWidgets.QTextBrowser(Dialog)
        self.textBrowser_4.setGeometry(QtCore.QRect(30, 320, 341, 261))
        self.textBrowser_4.setObjectName("textBrowser_4")
        self.chooseInputImage = QtWidgets.QPushButton(Dialog)
        self.chooseInputImage.setGeometry(QtCore.QRect(20, 240, 161, 41))
        self.chooseInputImage.setObjectName("chooseInputImage")
        self.textBrowser_5 = QtWidgets.QTextBrowser(Dialog)
        self.textBrowser_5.setGeometry(QtCore.QRect(1020, 20, 281, 31))
        self.textBrowser_5.setObjectName("textBrowser_5")
        self.textBrowser_6 = QtWidgets.QTextBrowser(Dialog)
        self.textBrowser_6.setGeometry(QtCore.QRect(1020, 60, 281, 221))
        self.textBrowser_6.setObjectName("textBrowser_6")
        self.textBrowser_7 = QtWidgets.QTextBrowser(Dialog)
        self.textBrowser_7.setGeometry(QtCore.QRect(1020, 320, 281, 391))
        self.textBrowser_7.setObjectName("textBrowser_7")
        self.newdomain = QtWidgets.QPushButton(Dialog)
        self.newdomain.setGeometry(QtCore.QRect(30, 660, 341, 41))
        self.newdomain.setObjectName("newdomain")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.clearSelection.setText(_translate("Dialog", "Clear Selection"))
        self.textBrowser.setHtml(_translate("Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Segoe UI\'; font-weight:696;\">User-guided segmentation</span><span style=\" font-family:\'Segoe UI\';\"><br /></span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Segoe UI\'; text-decoration: underline;\">Step 1</span><span style=\" font-family:\'Segoe UI\';\">: Draw a bounding box around the ROI.</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Segoe UI\'; text-decoration: underline;\">Step 2</span><span style=\" font-family:\'Segoe UI\';\">: Draw the ROI\'s outline and fill it in. </span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Segoe UI\'; text-decoration: underline;\">Step 3</span><span style=\" font-family:\'Segoe UI\';\">: The segmented image will be saved to the same directory as the input image.</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Segoe UI\'; text-decoration: underline;\">Step 4:</span><span style=\" font-family:\'Segoe UI\';\"> The saved image will be generated as a text file and saved in the same directory as the input image.</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Segoe UI\'; text-decoration: underline;\">Step 5</span><span style=\" font-family:\'Segoe UI\';\">: Clear the selection and go back to Step 1.</span></p></body></html>"))
        self.textBrowser_2.setHtml(_translate("Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Segoe UI\'; font-weight:696;\">ORIGINAL IMAGE</span></p></body></html>"))
        self.textBrowser_3.setHtml(_translate("Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Segoe UI\'; font-weight:696;\">SEGMENTED AREA</span></p></body></html>"))
        self.chooseEmbeddingDirs.setText(_translate("Dialog", "Choose Domains"))
        self.textBrowser_4.setHtml(_translate("Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Segoe UI\'; font-weight:696;\">t-SNE plot of source domain embeddings</span><span style=\" font-family:\'Segoe UI\';\"><br /></span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Segoe UI\'; text-decoration: underline;\">Step 1</span><span style=\" font-family:\'Segoe UI\';\">: Choose a set of directories containting embeddings to be plotted.</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'Segoe UI\';\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Segoe UI\'; text-decoration: underline;\">Step 2</span><span style=\" font-family:\'Segoe UI\';\">: A t-SNE plot of embeddings will be created.</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'Segoe UI\';\"><br /></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Segoe UI\'; font-size:10pt; font-weight:600;\">New domain</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Segoe UI\'; text-decoration: underline;\">Step 1:</span><span style=\" font-family:\'Segoe UI\';\"> Select a set of directories containing embeddings to be plotted and then select a file generated by a new image</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'Segoe UI\';\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Segoe UI\'; text-decoration: underline;\">Step 2: </span><span style=\" font-family:\'Segoe UI\';\">A new t-SNE plot will be created and the distances of the new points to each set of data in the embedding directory will be generated</span></p></body></html>"))
        self.chooseInputImage.setText(_translate("Dialog", "Choose Input Image"))
        self.textBrowser_5.setHtml(_translate("Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Segoe UI\'; font-weight:696;\">Feature Vector</span></p></body></html>"))
        self.newdomain.setText(_translate("Dialog", "New Domain"))
